[package]
name = "libvm"
version = "0.1.0"
authors = ["julio <julio.grillo98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vm"
crate-type = ["staticlib", "lib"]

[dependencies]
